name 'eaccelerator'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures eaccelerator'
long_description 'Installs/Configures eaccelerator'
version '0.1.0'
